[package]
name = "jumpcutter"
version = "0.1.2"
authors = ["Romain Déoux <romain.deoux@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
log = "0.4.20"
simple_logger = "4.2.0"
tempfile = "3.8.0"
