[package]
name = "jumpcutter"
version = "0.1.1"
authors = ["Romain Déoux <romain.deoux@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
log = "0.4.18"
simple_logger = "4.1.0"
tempfile = "3.5.0"
